import { NAvatar } from '@/app/assets/pngs';
import { NPayment } from '@/app/assets/svgs';

export const notificationsList = [
  // 15 April 2025
  {
    id: '1',
    type: 'message',
    name: '{Creative’s name}',
    message: 'sent you a message.',
    date: new Date('2025-04-15T16:15:00'),
    actionLabel: 'View Message',
    highlighted: true,
    avatarUrl: NAvatar,
  },
  {
    id: '2',
    type: 'invoice',
    name: '{Creative’s name}',
    message: 'just sent you an invoice.',
    date: new Date('2025-04-15T15:30:00'),
    actionLabel: 'View Invoice',
    avatarUrl: NAvatar,
  },
  {
    id: '3',
    type: 'payment',
    message: 'You have a payment of <strong>14,000</strong> due by Wednesday.',
    date: new Date('2025-04-15T15:00:00'),
    actionLabel: 'View Project',
    icon: NPayment,
  },

  // 12 April 2025
  {
    id: '4',
    type: 'message',
    name: '{Creative’s name}',
    message: 'followed up on your last message.',
    date: new Date('2025-04-12T14:20:00'),
    actionLabel: 'View Message',
    highlighted: true,
    avatarUrl: NAvatar,
  },
  {
    id: '5',
    type: 'invoice',
    name: '{Creative’s name}',
    message: 'sent you a revised invoice.',
    date: new Date('2025-04-12T13:50:00'),
    actionLabel: 'View Invoice',
    avatarUrl: NAvatar,
  },

  // 6 March 2024
  {
    id: '6',
    type: 'payment',
    message: 'Payment of <strong>10,000</strong> was successfully processed.',
    date: new Date('2024-03-06T10:10:00'),
    actionLabel: 'View Receipt',
    icon: NPayment,
  },
  {
    id: '7',
    type: 'message',
    name: '{Creative’s name}',
    message: 'sent a message regarding your milestone.',
    date: new Date('2024-03-06T09:30:00'),
    actionLabel: 'Reply',
    highlighted: true,
    avatarUrl: NAvatar,
  },

  // 18 January 2024
  {
    id: '8',
    type: 'invoice',
    name: '{Creative’s name}',
    message: 'marked an invoice as paid.',
    date: new Date('2024-01-18T17:05:00'),
    actionLabel: 'View Invoice',
    avatarUrl: NAvatar,
  },
  {
    id: '9',
    type: 'payment',
    message: 'You have a pending payment of <strong>5,500</strong> due Friday.',
    date: new Date('2024-01-18T15:45:00'),
    actionLabel: 'Pay Now',
    icon: NPayment,
  },

  // 22 December 2023
  {
    id: '10',
    type: 'message',
    name: '{Creative’s name}',
    message: 'wished you happy holidays!',
    date: new Date('2023-12-22T08:15:00'),
    actionLabel: 'View Message',
    avatarUrl: NAvatar,
  },
];

export const messageNotifications = [
  {
    id: '1',
    type: 'message',
    name: '{Creative’s name}',
    message: 'sent you a message.',
    date: new Date('2025-04-15T16:15:00'),
    actionLabel: 'View Message',
    highlighted: true,
    avatarUrl: NAvatar,
    onActionClick: () => { alert('Viewing message 1...') },
  },
  {
    id: '2',
    type: 'message',
    name: '{Creative’s name}',
    message: 'replied to your comment.',
    date: new Date('2025-04-15T13:02:00'),
    actionLabel: 'View Message',
    avatarUrl: NAvatar,
  },
  {
    id: '3',
    type: 'message',
    name: '{Creative’s name}',
    message: 'sent a new file for your review.',
    date: new Date('2025-04-14T09:30:00'),
    actionLabel: 'View Message',
    avatarUrl: NAvatar,
  },
  {
    id: '4',
    type: 'message',
    name: '{Creative’s name}',
    message: 'mentioned you in a thread.',
    date: new Date('2025-04-14T18:22:00'),
    actionLabel: 'View Message',
    avatarUrl: NAvatar,
  },
  {
    id: '5',
    type: 'message',
    name: '{Creative’s name}',
    message: 'sent a voice note.',
    date: new Date('2025-04-13T10:45:00'),
    actionLabel: 'View Message',
    avatarUrl: NAvatar,
  },
  {
    id: '6',
    type: 'message',
    name: '{Creative’s name}',
    message: 'shared a link with you.',
    date: new Date('2025-04-13T14:10:00'),
    actionLabel: 'View Message',
    avatarUrl: NAvatar,
  },
  {
    id: '7',
    type: 'message',
    name: '{Creative’s name}',
    message: 'sent you feedback on your design.',
    date: new Date('2025-04-12T12:00:00'),
    actionLabel: 'View Message',
    avatarUrl: NAvatar,
  },
  {
    id: '8',
    type: 'message',
    name: '{Creative’s name}',
    message: 'asked a question about your proposal.',
    date: new Date('2025-04-12T17:45:00'),
    actionLabel: 'View Message',
    avatarUrl: NAvatar,
  },
  {
    id: '9',
    type: 'message',
    name: '{Creative’s name}',
    message: 'reacted to your message.',
    date: new Date('2025-04-11T15:30:00'),
    avatarUrl: NAvatar,
    actionLabel: 'View Message',
  },
  {
    id: '10',
    type: 'message',
    name: '{Creative’s name}',
    message: 'started a new conversation.',
    date: new Date('2025-04-10T11:20:00'),
    actionLabel: 'View Message',
    avatarUrl: NAvatar,
  },
];
