/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all chats for the logged-in user */
        get: {
            parameters: {
                query?: {
                    PageNumber?: number;
                    PageSize?: number;
                    SearchKey?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ChatModelPagedListBaseResponse"];
                        "application/json": components["schemas"]["ChatModelPagedListBaseResponse"];
                        "text/json": components["schemas"]["ChatModelPagedListBaseResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Start a new chat */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["StartChatCommand"];
                    "application/json": components["schemas"]["StartChatCommand"];
                    "text/json": components["schemas"]["StartChatCommand"];
                    "application/*+json": components["schemas"]["StartChatCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ChatModelBaseResponse"];
                        "application/json": components["schemas"]["ChatModelBaseResponse"];
                        "text/json": components["schemas"]["ChatModelBaseResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chats/{chatId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get chat by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    chatId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ChatModelBaseResponse"];
                        "application/json": components["schemas"]["ChatModelBaseResponse"];
                        "text/json": components["schemas"]["ChatModelBaseResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chats/{chatId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all messages for a chat */
        get: {
            parameters: {
                query?: {
                    IsRead?: boolean;
                    PageNumber?: number;
                    PageSize?: number;
                    SearchKey?: string;
                };
                header?: never;
                path: {
                    chatId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageModelPagedListBaseResponse"];
                        "application/json": components["schemas"]["MessageModelPagedListBaseResponse"];
                        "text/json": components["schemas"]["MessageModelPagedListBaseResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Send message to a chat */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    chatId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: uuid */
                        ChatId?: string;
                        Content?: string;
                        Attachments?: string[];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageModelBaseResponse"];
                        "application/json": components["schemas"]["MessageModelBaseResponse"];
                        "text/json": components["schemas"]["MessageModelBaseResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user notifications */
        get: {
            parameters: {
                query?: {
                    IsRead?: boolean;
                    PageNumber?: number;
                    PageSize?: number;
                    SearchKey?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["NotificationModelPagedListBaseResponse"];
                        "application/json": components["schemas"]["NotificationModelPagedListBaseResponse"];
                        "text/json": components["schemas"]["NotificationModelPagedListBaseResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/unread-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get unread user notifications count */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Int32BaseResponse"];
                        "application/json": components["schemas"]["Int32BaseResponse"];
                        "text/json": components["schemas"]["Int32BaseResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{notificationId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Read user notification */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    notificationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UnitBaseResponse"];
                        "application/json": components["schemas"]["UnitBaseResponse"];
                        "text/json": components["schemas"]["UnitBaseResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/mark-all-read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Mark all user notifications read */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UnitBaseResponse"];
                        "application/json": components["schemas"]["UnitBaseResponse"];
                        "text/json": components["schemas"]["UnitBaseResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ChatModel: {
            /** Format: uuid */
            id?: string;
            sender?: components["schemas"]["UserDto"];
            receiver?: components["schemas"]["UserDto"];
            /** Format: date-time */
            lastMessageTime?: string | null;
            lastMessagePreview?: string | null;
            hasUnreadMessages?: boolean;
            /** Format: int32 */
            unreadMessagesCount?: number;
        };
        ChatModelBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["ChatModel"];
            metaData?: unknown;
        };
        ChatModelPagedListBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["ChatModel"][] | null;
            metaData?: unknown;
        };
        Int32BaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            /** Format: int32 */
            data?: number;
            metaData?: unknown;
        };
        MessageAttachmentModel: {
            /** Format: uuid */
            id?: string;
            fileName?: string | null;
            filePathUrl?: string | null;
            fileType?: string | null;
            fileSize?: string | null;
            createdDate?: string | null;
        };
        MessageModel: {
            /** Format: uuid */
            id?: string;
            content?: string | null;
            userId?: string | null;
            /** Format: date-time */
            sentAt?: string;
            isRead?: boolean;
            /** Format: date-time */
            createdDate?: string;
            attachments?: components["schemas"]["MessageAttachmentModel"][] | null;
        };
        MessageModelBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["MessageModel"];
            metaData?: unknown;
        };
        MessageModelPagedListBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["MessageModel"][] | null;
            metaData?: unknown;
        };
        NotificationModel: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            createdDate?: string;
            createdBy?: string | null;
            /** Format: date-time */
            modifiedDate?: string | null;
            modifiedBy?: string | null;
            isDeleted?: boolean;
            /** Format: date-time */
            deletedDate?: string | null;
            deletedBy?: string | null;
            sourceName?: string | null;
            sourceAvatar?: string | null;
            title: string | null;
            type?: components["schemas"]["NotificationTypeEnums"];
            objectId?: string | null;
            objectSlug?: string | null;
            objectIdentifier?: string | null;
            isRead?: boolean;
            content?: string | null;
            /** Format: date-time */
            readAt?: string | null;
            userId?: string | null;
        };
        NotificationModelPagedListBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["NotificationModel"][] | null;
            metaData?: unknown;
        };
        /** @enum {string} */
        NotificationTypeEnums: "Message" | "ProjectComment";
        StartChatCommand: {
            receiverUserId?: string | null;
        };
        Unit: Record<string, never>;
        UnitBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["Unit"];
            metaData?: unknown;
        };
        UserDto: {
            id: string | null;
            firstName: string | null;
            profilePicture?: string | null;
            lastName: string | null;
            /** Format: uuid */
            actorId?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
