/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/projects/{projectId}/agreements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all agreements for a project */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AgreementModelIEnumerableBaseResponse"];
                        "application/json": components["schemas"]["AgreementModelIEnumerableBaseResponse"];
                        "text/json": components["schemas"]["AgreementModelIEnumerableBaseResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create an agreement */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: uuid */
                        ProjectId?: string;
                        /** Format: binary */
                        Document: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AgreementModelBaseResponse"];
                        "application/json": components["schemas"]["AgreementModelBaseResponse"];
                        "text/json": components["schemas"]["AgreementModelBaseResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/agreements/{agreementId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get agreement by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    agreementId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AgreementModelBaseResponse"];
                        "application/json": components["schemas"]["AgreementModelBaseResponse"];
                        "text/json": components["schemas"]["AgreementModelBaseResponse"];
                    };
                };
            };
        };
        /** Update an agreement */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    agreementId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: uuid */
                        Id?: string;
                        /** Format: binary */
                        Document?: string;
                        /** Format: uuid */
                        ProjectId?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AgreementModelBaseResponse"];
                        "application/json": components["schemas"]["AgreementModelBaseResponse"];
                        "text/json": components["schemas"]["AgreementModelBaseResponse"];
                    };
                };
            };
        };
        post?: never;
        /** Delete an agreement */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    agreementId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UnitBaseResponse"];
                        "application/json": components["schemas"]["UnitBaseResponse"];
                        "text/json": components["schemas"]["UnitBaseResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clientmanagement/create-client": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create client */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        Name: string;
                        Email: string;
                        /** Format: binary */
                        Avatar?: string;
                        PhoneNumber?: string;
                        /** Format: int32 */
                        Birthday?: number;
                        BirthMonth?: components["schemas"]["MonthEnums"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MyClientModelBaseResponse"];
                        "application/json": components["schemas"]["MyClientModelBaseResponse"];
                        "text/json": components["schemas"]["MyClientModelBaseResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clientmanagement/update-client": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update client */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        Name?: string;
                        Email?: string;
                        PhoneNumber?: string;
                        /** Format: int32 */
                        Birthday?: number;
                        BirthMonth?: components["schemas"]["MonthEnums"];
                        ClientUserId?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MyClientModelBaseResponse"];
                        "application/json": components["schemas"]["MyClientModelBaseResponse"];
                        "text/json": components["schemas"]["MyClientModelBaseResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clientmanagement/my-clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get my clients */
        get: {
            parameters: {
                query?: {
                    Birthday?: number;
                    BirthMonth?: components["schemas"]["MonthEnums"];
                    PageNumber?: number;
                    PageSize?: number;
                    SearchKey?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MyClientModelPagedListBaseResponse"];
                        "application/json": components["schemas"]["MyClientModelPagedListBaseResponse"];
                        "text/json": components["schemas"]["MyClientModelPagedListBaseResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clientmanagement/delete-client": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete my client */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["DeleteMyClientCommand"];
                    "application/json": components["schemas"]["DeleteMyClientCommand"];
                    "text/json": components["schemas"]["DeleteMyClientCommand"];
                    "application/*+json": components["schemas"]["DeleteMyClientCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UnitBaseResponse"];
                        "application/json": components["schemas"]["UnitBaseResponse"];
                        "text/json": components["schemas"]["UnitBaseResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all comments for a project */
        get: {
            parameters: {
                query?: {
                    PageNumber?: number;
                    PageSize?: number;
                    SearchKey?: string;
                };
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CommentModelPagedListBaseResponse"];
                        "application/json": components["schemas"]["CommentModelPagedListBaseResponse"];
                        "text/json": components["schemas"]["CommentModelPagedListBaseResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create a comment */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["CreateCommentCommand"];
                    "application/json": components["schemas"]["CreateCommentCommand"];
                    "text/json": components["schemas"]["CreateCommentCommand"];
                    "application/*+json": components["schemas"]["CreateCommentCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CommentModelBaseResponse"];
                        "application/json": components["schemas"]["CommentModelBaseResponse"];
                        "text/json": components["schemas"]["CommentModelBaseResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a comment */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    commentId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["UpdateCommentCommand"];
                    "application/json": components["schemas"]["UpdateCommentCommand"];
                    "text/json": components["schemas"]["UpdateCommentCommand"];
                    "application/*+json": components["schemas"]["UpdateCommentCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CommentModelBaseResponse"];
                        "application/json": components["schemas"]["CommentModelBaseResponse"];
                        "text/json": components["schemas"]["CommentModelBaseResponse"];
                    };
                };
            };
        };
        post?: never;
        /** Delete a comment */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    commentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UnitBaseResponse"];
                        "application/json": components["schemas"]["UnitBaseResponse"];
                        "text/json": components["schemas"]["UnitBaseResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/deliverables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all deliverables for a project */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DeliverableModelIEnumerableBaseResponse"];
                        "application/json": components["schemas"]["DeliverableModelIEnumerableBaseResponse"];
                        "text/json": components["schemas"]["DeliverableModelIEnumerableBaseResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create a deliverable */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["CreateDeliverableCommand"];
                    "application/json": components["schemas"]["CreateDeliverableCommand"];
                    "text/json": components["schemas"]["CreateDeliverableCommand"];
                    "application/*+json": components["schemas"]["CreateDeliverableCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DeliverableModelBaseResponse"];
                        "application/json": components["schemas"]["DeliverableModelBaseResponse"];
                        "text/json": components["schemas"]["DeliverableModelBaseResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/deliverables/{deliverableId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get deliverable by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    deliverableId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DeliverableModelBaseResponse"];
                        "application/json": components["schemas"]["DeliverableModelBaseResponse"];
                        "text/json": components["schemas"]["DeliverableModelBaseResponse"];
                    };
                };
            };
        };
        /** Update a deliverable */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    deliverableId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["UpdateDeliverableCommand"];
                    "application/json": components["schemas"]["UpdateDeliverableCommand"];
                    "text/json": components["schemas"]["UpdateDeliverableCommand"];
                    "application/*+json": components["schemas"]["UpdateDeliverableCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DeliverableModelBaseResponse"];
                        "application/json": components["schemas"]["DeliverableModelBaseResponse"];
                        "text/json": components["schemas"]["DeliverableModelBaseResponse"];
                    };
                };
            };
        };
        post?: never;
        /** Delete a deliverable */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    deliverableId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UnitBaseResponse"];
                        "application/json": components["schemas"]["UnitBaseResponse"];
                        "text/json": components["schemas"]["UnitBaseResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/deliverables/{deliverableId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all tasks for a deliverable */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    deliverableId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DeliverableTaskModelIEnumerableBaseResponse"];
                        "application/json": components["schemas"]["DeliverableTaskModelIEnumerableBaseResponse"];
                        "text/json": components["schemas"]["DeliverableTaskModelIEnumerableBaseResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create a task */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    deliverableId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["CreateDeliverableTaskCommand"];
                    "application/json": components["schemas"]["CreateDeliverableTaskCommand"];
                    "text/json": components["schemas"]["CreateDeliverableTaskCommand"];
                    "application/*+json": components["schemas"]["CreateDeliverableTaskCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DeliverableTaskModelBaseResponse"];
                        "application/json": components["schemas"]["DeliverableTaskModelBaseResponse"];
                        "text/json": components["schemas"]["DeliverableTaskModelBaseResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/deliverables/{deliverableId}/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get task by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    deliverableId: string;
                    taskId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DeliverableTaskModelBaseResponse"];
                        "application/json": components["schemas"]["DeliverableTaskModelBaseResponse"];
                        "text/json": components["schemas"]["DeliverableTaskModelBaseResponse"];
                    };
                };
            };
        };
        /** Update a task */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    deliverableId: string;
                    taskId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["UpdateDeliverableTaskCommand"];
                    "application/json": components["schemas"]["UpdateDeliverableTaskCommand"];
                    "text/json": components["schemas"]["UpdateDeliverableTaskCommand"];
                    "application/*+json": components["schemas"]["UpdateDeliverableTaskCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DeliverableTaskModelBaseResponse"];
                        "application/json": components["schemas"]["DeliverableTaskModelBaseResponse"];
                        "text/json": components["schemas"]["DeliverableTaskModelBaseResponse"];
                    };
                };
            };
        };
        post?: never;
        /** Delete a task */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    deliverableId: string;
                    taskId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UnitBaseResponse"];
                        "application/json": components["schemas"]["UnitBaseResponse"];
                        "text/json": components["schemas"]["UnitBaseResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/extra-costs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all extra costs for a project */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ExtraCostModelIEnumerableBaseResponse"];
                        "application/json": components["schemas"]["ExtraCostModelIEnumerableBaseResponse"];
                        "text/json": components["schemas"]["ExtraCostModelIEnumerableBaseResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create an extra cost */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["CreateExtraCostCommand"];
                    "application/json": components["schemas"]["CreateExtraCostCommand"];
                    "text/json": components["schemas"]["CreateExtraCostCommand"];
                    "application/*+json": components["schemas"]["CreateExtraCostCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ExtraCostModelBaseResponse"];
                        "application/json": components["schemas"]["ExtraCostModelBaseResponse"];
                        "text/json": components["schemas"]["ExtraCostModelBaseResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/extra-costs/{extraCostId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get extra cost by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    extraCostId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ExtraCostModelBaseResponse"];
                        "application/json": components["schemas"]["ExtraCostModelBaseResponse"];
                        "text/json": components["schemas"]["ExtraCostModelBaseResponse"];
                    };
                };
            };
        };
        /** Update an extra cost */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    extraCostId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["UpdateExtraCostCommand"];
                    "application/json": components["schemas"]["UpdateExtraCostCommand"];
                    "text/json": components["schemas"]["UpdateExtraCostCommand"];
                    "application/*+json": components["schemas"]["UpdateExtraCostCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ExtraCostModelBaseResponse"];
                        "application/json": components["schemas"]["ExtraCostModelBaseResponse"];
                        "text/json": components["schemas"]["ExtraCostModelBaseResponse"];
                    };
                };
            };
        };
        post?: never;
        /** Delete an extra cost */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    extraCostId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UnitBaseResponse"];
                        "application/json": components["schemas"]["UnitBaseResponse"];
                        "text/json": components["schemas"]["UnitBaseResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all invoices with given optional params */
        get: {
            parameters: {
                query?: {
                    Status?: components["schemas"]["InvoiceStatusEnums"];
                    PageNumber?: number;
                    PageSize?: number;
                    SearchKey?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["InvoiceMiniModelPagedListBaseResponse"];
                        "application/json": components["schemas"]["InvoiceMiniModelPagedListBaseResponse"];
                        "text/json": components["schemas"]["InvoiceMiniModelPagedListBaseResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/{invoiceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get invoice by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    invoiceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["InvoiceModelBaseResponse"];
                        "application/json": components["schemas"]["InvoiceModelBaseResponse"];
                        "text/json": components["schemas"]["InvoiceModelBaseResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/payment-schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all payment schedules for a project */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PaymentScheduleModelIEnumerableBaseResponse"];
                        "application/json": components["schemas"]["PaymentScheduleModelIEnumerableBaseResponse"];
                        "text/json": components["schemas"]["PaymentScheduleModelIEnumerableBaseResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create a payment schedule */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["CreatePaymentScheduleCommand"];
                    "application/json": components["schemas"]["CreatePaymentScheduleCommand"];
                    "text/json": components["schemas"]["CreatePaymentScheduleCommand"];
                    "application/*+json": components["schemas"]["CreatePaymentScheduleCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PaymentScheduleModelBaseResponse"];
                        "application/json": components["schemas"]["PaymentScheduleModelBaseResponse"];
                        "text/json": components["schemas"]["PaymentScheduleModelBaseResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/payment-schedules/{paymentScheduleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get payment schedule by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    paymentScheduleId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PaymentScheduleModelBaseResponse"];
                        "application/json": components["schemas"]["PaymentScheduleModelBaseResponse"];
                        "text/json": components["schemas"]["PaymentScheduleModelBaseResponse"];
                    };
                };
            };
        };
        /** Update a payment schedule */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    paymentScheduleId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["UpdatePaymentScheduleCommand"];
                    "application/json": components["schemas"]["UpdatePaymentScheduleCommand"];
                    "text/json": components["schemas"]["UpdatePaymentScheduleCommand"];
                    "application/*+json": components["schemas"]["UpdatePaymentScheduleCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PaymentScheduleModelBaseResponse"];
                        "application/json": components["schemas"]["PaymentScheduleModelBaseResponse"];
                        "text/json": components["schemas"]["PaymentScheduleModelBaseResponse"];
                    };
                };
            };
        };
        post?: never;
        /** Delete a payment schedule */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    paymentScheduleId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UnitBaseResponse"];
                        "application/json": components["schemas"]["UnitBaseResponse"];
                        "text/json": components["schemas"]["UnitBaseResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all projects with given optional params */
        get: {
            parameters: {
                query?: {
                    Type?: components["schemas"]["ProjectTypeEnums"];
                    Status?: components["schemas"]["StatusEnums"];
                    Priority?: components["schemas"]["ProjectPriorityEnums"];
                    Currency?: components["schemas"]["CurrencyEnums"];
                    PageNumber?: number;
                    PageSize?: number;
                    SearchKey?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProjectMiniModelPagedListBaseResponse"];
                        "application/json": components["schemas"]["ProjectMiniModelPagedListBaseResponse"];
                        "text/json": components["schemas"]["ProjectMiniModelPagedListBaseResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create a project */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["CreateProjectCommand"];
                    "application/json": components["schemas"]["CreateProjectCommand"];
                    "text/json": components["schemas"]["CreateProjectCommand"];
                    "application/*+json": components["schemas"]["CreateProjectCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProjectModelBaseResponse"];
                        "application/json": components["schemas"]["ProjectModelBaseResponse"];
                        "text/json": components["schemas"]["ProjectModelBaseResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get project by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProjectModelBaseResponse"];
                        "application/json": components["schemas"]["ProjectModelBaseResponse"];
                        "text/json": components["schemas"]["ProjectModelBaseResponse"];
                    };
                };
            };
        };
        /** Update a project */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["UpdateProjectCommand"];
                    "application/json": components["schemas"]["UpdateProjectCommand"];
                    "text/json": components["schemas"]["UpdateProjectCommand"];
                    "application/*+json": components["schemas"]["UpdateProjectCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProjectModelBaseResponse"];
                        "application/json": components["schemas"]["ProjectModelBaseResponse"];
                        "text/json": components["schemas"]["ProjectModelBaseResponse"];
                    };
                };
            };
        };
        post?: never;
        /** Delete a project */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UnitBaseResponse"];
                        "application/json": components["schemas"]["UnitBaseResponse"];
                        "text/json": components["schemas"]["UnitBaseResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}/rate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rate a project */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["RateProjectCommand"];
                    "application/json": components["schemas"]["RateProjectCommand"];
                    "text/json": components["schemas"]["RateProjectCommand"];
                    "application/*+json": components["schemas"]["RateProjectCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UnitBaseResponse"];
                        "application/json": components["schemas"]["UnitBaseResponse"];
                        "text/json": components["schemas"]["UnitBaseResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AgreementModel: {             
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            createdDate?: string;
            createdBy?: string | null;
            /** Format: date-time */
            modifiedDate?: string | null;
            modifiedBy?: string | null;
            isDeleted?: boolean;
            /** Format: date-time */
            deletedDate?: string | null;
            deletedBy?: string | null;
            title?: string | null;
            description?: string | null;
            documentUrl?: string | null;
            /** Format: uuid */
            projectId?: string;
        };
        AgreementModelBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["AgreementModel"];
            metaData?: unknown;
        };
        AgreementModelIEnumerableBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["AgreementModel"][] | null;
            metaData?: unknown;
        };
        CommentMentionModel: {
            /** Format: uuid */
            id?: string;
            userId: string | null;
        };
        CommentModel: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            createdDate?: string;
            createdBy?: string | null;
            /** Format: date-time */
            modifiedDate?: string | null;
            modifiedBy?: string | null;
            isDeleted?: boolean;
            /** Format: date-time */
            deletedDate?: string | null;
            deletedBy?: string | null;
            content: string | null;
            user?: components["schemas"]["UserDto"];
            /** Format: uuid */
            projectId?: string;
            mentions?: components["schemas"]["CommentMentionModel"][] | null;
        };
        CommentModelBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["CommentModel"];
            metaData?: unknown;
        };
        CommentModelPagedListBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["CommentModel"][] | null;
            metaData?: unknown;
        };
        CreateCommentCommand: {
            content: string | null;
            /** Format: uuid */
            projectId?: string | null;
        };
        CreateDeliverableCommand: {
            /** Format: uuid */
            projectId?: string;
            name: string | null;
            description?: string | null;
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
            /** Format: double */
            unitAmount?: number;
            /** Format: int32 */
            unit?: number;
        };
        CreateDeliverableTaskCommand: {
            name: string | null;
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
            priority?: components["schemas"]["ProjectPriorityEnums"];
            /** Format: uuid */
            deliverableId?: string | null;
            /** Format: uuid */
            projectId?: string | null;
        };
        CreateExtraCostCommand: {
            name: string | null;
            description?: string | null;
            /** Format: double */
            amount?: number;
            /** Format: uuid */
            projectId?: string;
        };
        CreatePaymentScheduleCommand: {
            /** Format: double */
            amount?: number;
            /** Format: date-time */
            dueDate?: string;
            /** Format: uuid */
            projectId?: string;
        };
        CreateProjectCommand: {
            title: string | null;
            description?: string | null;
            /** Format: date-time */
            startDate?: string | null;
            /** Format: date-time */
            expectedDeliveryDate?: string | null;
            type?: components["schemas"]["ProjectTypeEnums"];
            priority?: components["schemas"]["ProjectPriorityEnums"];
            clientUserId?: string | null;
        };
        /** @enum {string} */
        CurrencyEnums: "AUD" | "CAD" | "EUR" | "GBP" | "JPY" | "NGN" | "USD";
        DeleteMyClientCommand: {
            clientUserId?: string | null;
        };
        DeliverableModel: {
            /** Format: uuid */
            id?: string;
            name: string | null;
            description?: string | null;
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
            priority?: components["schemas"]["ProjectPriorityEnums"];
            status?: components["schemas"]["StatusEnums"];
            /** Format: double */
            unitAmount?: number;
            /** Format: int32 */
            unit?: number;
            /** Format: double */
            total?: number;
        };
        DeliverableModelBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["DeliverableModel"];
            metaData?: unknown;
        };
        DeliverableModelIEnumerableBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["DeliverableModel"][] | null;
            metaData?: unknown;
        };
        DeliverableTaskModel: {
            /** Format: uuid */
            id?: string;
            name: string | null;
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
            priority?: components["schemas"]["ProjectPriorityEnums"];
            status?: components["schemas"]["StatusEnums"];
        };
        DeliverableTaskModelBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["DeliverableTaskModel"];
            metaData?: unknown;
        };
        DeliverableTaskModelIEnumerableBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["DeliverableTaskModel"][] | null;
            metaData?: unknown;
        };
        ExtraCostModel: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            createdDate?: string;
            createdBy?: string | null;
            /** Format: date-time */
            modifiedDate?: string | null;
            modifiedBy?: string | null;
            isDeleted?: boolean;
            /** Format: date-time */
            deletedDate?: string | null;
            deletedBy?: string | null;
            name: string | null;
            description?: string | null;
            /** Format: double */
            amount?: number;
            /** Format: uuid */
            projectId?: string;
        };
        ExtraCostModelBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["ExtraCostModel"];
            metaData?: unknown;
        };
        ExtraCostModelIEnumerableBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["ExtraCostModel"][] | null;
            metaData?: unknown;
        };
        InvoiceMiniModel: {
            /** Format: uuid */
            id?: string;
            status?: components["schemas"]["InvoiceStatusEnums"];
            clientUser?: components["schemas"]["UserDto"];
            creativeUser?: components["schemas"]["UserDto"];
            paymentSchedule?: components["schemas"]["PaymentScheduleInvoiceMiniModel"];
        };
        InvoiceMiniModelPagedListBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["InvoiceMiniModel"][] | null;
            metaData?: unknown;
        };
        InvoiceModel: {
            /** Format: uuid */
            id?: string;
            status?: components["schemas"]["InvoiceStatusEnums"];
            clientUser?: components["schemas"]["UserDto"];
            creativeUser?: components["schemas"]["UserDto"];
            paymentSchedule?: components["schemas"]["PaymentScheduleInvoiceModel"];
        };
        InvoiceModelBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["InvoiceModel"];
            metaData?: unknown;
        };
        /** @enum {string} */
        InvoiceStatusEnums: "Closed" | "Due" | "Pending";
        /** @enum {string} */
        MonthEnums: "April" | "August" | "December" | "February" | "January" | "July" | "June" | "March" | "May" | "November" | "October" | "September";
        MyClientModel: {
            name?: string | null;
            email?: string | null;
            avatarUrl?: string | null;
            phoneNumber?: string | null;
            /** Format: int32 */
            birthday?: number;
            birthMonth?: components["schemas"]["MonthEnums"];
            clientUserId?: string | null;
        };
        MyClientModelBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["MyClientModel"];
            metaData?: unknown;
        };
        MyClientModelPagedListBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["MyClientModel"][] | null;
            metaData?: unknown;
        };
        PaymentScheduleInvoiceMiniModel: {
            /** Format: double */
            amount?: number;
            /** Format: date-time */
            dueDate?: string;
            status?: components["schemas"]["PaymentStatusEnums"];
            project?: components["schemas"]["ProjectMiniInvoiceModel"];
        };
        PaymentScheduleInvoiceModel: {
            /** Format: double */
            amount?: number;
            /** Format: date-time */
            dueDate?: string;
            status?: components["schemas"]["PaymentStatusEnums"];
            project?: components["schemas"]["ProjectInvoiceModel"];
        };
        PaymentScheduleModel: {
            /** Format: uuid */
            id?: string;
            /** Format: double */
            amount?: number;
            /** Format: date-time */
            dueDate?: string;
            status?: components["schemas"]["PaymentStatusEnums"];
            /** Format: double */
            paidAmount?: number | null;
            /** Format: double */
            remainingAmount?: number | null;
            /** Format: date-time */
            createdDate?: string;
        };
        PaymentScheduleModelBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["PaymentScheduleModel"];
            metaData?: unknown;
        };
        PaymentScheduleModelIEnumerableBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["PaymentScheduleModel"][] | null;
            metaData?: unknown;
        };
        /** @enum {string} */
        PaymentStatusEnums: "Cancelled" | "Due" | "Failed" | "Overdue" | "Paid" | "PartiallyPaid" | "Pending" | "Refunded";
        ProjectInvoiceModel: {
            /** Format: uuid */
            id?: string;
            title: string | null;
            deliverables?: components["schemas"]["DeliverableModel"][] | null;
        };
        ProjectMetric: {
            /** Format: int32 */
            daysLeft?: number;
            readonly daysLeftDisplay?: string | null;
            readonly isEndNear?: boolean;
            readonly isOverdue?: boolean;
            /** Format: double */
            progressPercent?: number;
            readonly progressPercentDisplay?: string | null;
        };
        ProjectMiniInvoiceModel: {
            /** Format: uuid */
            id?: string;
            title: string | null;
        };
        ProjectMiniModel: {
            /** Format: uuid */
            id?: string;
            title: string | null;
            description?: string | null;
            /** Format: date-time */
            startDate?: string | null;
            /** Format: date-time */
            expectedDeliveryDate?: string | null;
            type?: components["schemas"]["ProjectTypeEnums"];
            status?: components["schemas"]["StatusEnums"];
            priority?: components["schemas"]["ProjectPriorityEnums"];
            /** Format: double */
            actualCost?: number | null;
            creativeUser?: components["schemas"]["UserDto"];
            clientUser?: components["schemas"]["UserDto"];
            /** Format: date-time */
            createdDate?: string;
        };
        ProjectMiniModelPagedListBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["ProjectMiniModel"][] | null;
            metaData?: unknown;
        };
        ProjectModel: {
            /** Format: uuid */
            id?: string;
            title: string | null;
            description?: string | null;
            /** Format: date-time */
            startDate?: string | null;
            /** Format: date-time */
            expectedDeliveryDate?: string | null;
            type?: components["schemas"]["ProjectTypeEnums"];
            status?: components["schemas"]["StatusEnums"];
            priority?: components["schemas"]["ProjectPriorityEnums"];
            /** Format: double */
            actualCost?: number | null;
            creativeUser?: components["schemas"]["UserDto"];
            clientUser?: components["schemas"]["UserDto"];
            /** Format: date-time */
            createdDate?: string;
            deliverables?: components["schemas"]["DeliverableModel"][] | null;
            paymentSchedules?: components["schemas"]["PaymentScheduleModel"][] | null;
            metrics?: components["schemas"]["ProjectMetric"];
        };
        ProjectModelBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["ProjectModel"];
            metaData?: unknown;
        };
        /** @enum {string} */
        ProjectPriorityEnums: "High" | "Low" | "Medium";
        /** @enum {string} */
        ProjectTypeEnums: "Client" | "Personal";
        RateProjectCommand: {
            /** Format: uuid */
            projectId?: string;
            /** Format: int32 */
            rating?: number;
            review?: string | null;
        };
        /** @enum {string} */
        StatusEnums: "Archived" | "Cancelled" | "Completed" | "Due" | "InProgress" | "OnHold" | "Pending" | "ToDo";
        Unit: Record<string, never>;
        UnitBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["Unit"];
            metaData?: unknown;
        };
        UpdateCommentCommand: {
            /** Format: uuid */
            id?: string;
            content: string | null;
            /** Format: uuid */
            projectId?: string | null;
        };
        UpdateDeliverableCommand: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            description?: string | null;
            /** Format: date-time */
            startDate?: string | null;
            /** Format: date-time */
            endDate?: string | null;
            priority?: components["schemas"]["ProjectPriorityEnums"];
            status?: components["schemas"]["StatusEnums"];
            /** Format: double */
            unitAmount?: number | null;
            /** Format: int32 */
            unit?: number | null;
        };
        UpdateDeliverableTaskCommand: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
            priority?: components["schemas"]["ProjectPriorityEnums"];
            status?: components["schemas"]["StatusEnums"];
            /** Format: uuid */
            deliverableId?: string | null;
            /** Format: uuid */
            projectId?: string | null;
        };
        UpdateExtraCostCommand: {
            /** Format: uuid */
            id?: string;
            name: string | null;
            description?: string | null;
            /** Format: double */
            amount?: number;
            /** Format: uuid */
            projectId?: string | null;
        };
        UpdatePaymentScheduleCommand: {
            /** Format: uuid */
            id?: string;
            /** Format: double */
            amount?: number;
            /** Format: date-time */
            dueDate?: string;
            /** Format: uuid */
            projectId?: string | null;
        };
        UpdateProjectCommand: {
            /** Format: uuid */
            id?: string | null;
            title: string | null;
            description?: string | null;
            /** Format: date-time */
            startDate?: string | null;
            /** Format: date-time */
            expectedDeliveryDate?: string | null;
            /** Format: date-time */
            actualDeliveryDate?: string | null;
            status?: components["schemas"]["StatusEnums"];
            priority?: components["schemas"]["ProjectPriorityEnums"];
        };
        UserDto: {
            id: string | null;
            firstName: string | null;
            profilePicture?: string | null;
            lastName: string | null;
            /** Format: uuid */
            actorId?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
