/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/bankinstructions/transaction-notification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transaction Notification */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["TransactionNotificationCommand"];
                    "application/json": components["schemas"]["TransactionNotificationCommand"];
                    "text/json": components["schemas"]["TransactionNotificationCommand"];
                    "application/*+json": components["schemas"]["TransactionNotificationCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TransactionNotificationModel"];
                        "application/json": components["schemas"]["TransactionNotificationModel"];
                        "text/json": components["schemas"]["TransactionNotificationModel"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bankinstructions/account-lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Account Lookup */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["AccountLookUpQuery"];
                    "application/json": components["schemas"]["AccountLookUpQuery"];
                    "text/json": components["schemas"]["AccountLookUpQuery"];
                    "application/*+json": components["schemas"]["AccountLookUpQuery"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AccountLookUpModel"];
                        "application/json": components["schemas"]["AccountLookUpModel"];
                        "text/json": components["schemas"]["AccountLookUpModel"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bankinstructions/mini-statement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Mini Statement */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["MiniStatementQuery"];
                    "application/json": components["schemas"]["MiniStatementQuery"];
                    "text/json": components["schemas"]["MiniStatementQuery"];
                    "application/*+json": components["schemas"]["MiniStatementQuery"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MiniStatementModel"];
                        "application/json": components["schemas"]["MiniStatementModel"];
                        "text/json": components["schemas"]["MiniStatementModel"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bankinstructions/kyc-details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get KYC Details */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["GetKYCDetailsQuery"];
                    "application/json": components["schemas"]["GetKYCDetailsQuery"];
                    "text/json": components["schemas"]["GetKYCDetailsQuery"];
                    "application/*+json": components["schemas"]["GetKYCDetailsQuery"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["KYCDetailsModel"];
                        "application/json": components["schemas"]["KYCDetailsModel"];
                        "text/json": components["schemas"]["KYCDetailsModel"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bankinstructions/block-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Block Account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["BlockAccountCommand"];
                    "application/json": components["schemas"]["BlockAccountCommand"];
                    "text/json": components["schemas"]["BlockAccountCommand"];
                    "application/*+json": components["schemas"]["BlockAccountCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BlockAccountModel"];
                        "application/json": components["schemas"]["BlockAccountModel"];
                        "text/json": components["schemas"]["BlockAccountModel"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bankinstructions/unblock-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unblock Account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["UnblockAccountCommand"];
                    "application/json": components["schemas"]["UnblockAccountCommand"];
                    "text/json": components["schemas"]["UnblockAccountCommand"];
                    "application/*+json": components["schemas"]["UnblockAccountCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BlockAccountModel"];
                        "application/json": components["schemas"]["BlockAccountModel"];
                        "text/json": components["schemas"]["BlockAccountModel"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/beneficiarymanagement/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get my beneficiaries */
        get: {
            parameters: {
                query?: {
                    PageNumber?: number;
                    PageSize?: number;
                    SearchKey?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BeneficiaryModelPagedListBaseResponse"];
                        "application/json": components["schemas"]["BeneficiaryModelPagedListBaseResponse"];
                        "text/json": components["schemas"]["BeneficiaryModelPagedListBaseResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/beneficiarymanagement/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a beneficiary */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["CreateBeneficiaryCommand"];
                    "application/json": components["schemas"]["CreateBeneficiaryCommand"];
                    "text/json": components["schemas"]["CreateBeneficiaryCommand"];
                    "application/*+json": components["schemas"]["CreateBeneficiaryCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BeneficiaryModelBaseResponse"];
                        "application/json": components["schemas"]["BeneficiaryModelBaseResponse"];
                        "text/json": components["schemas"]["BeneficiaryModelBaseResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BeneficiaryModelBaseResponse"];
                        "application/json": components["schemas"]["BeneficiaryModelBaseResponse"];
                        "text/json": components["schemas"]["BeneficiaryModelBaseResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/beneficiarymanagement/delete/{accountNumber}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a beneficiary */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountNumber: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BooleanBaseResponse"];
                        "application/json": components["schemas"]["BooleanBaseResponse"];
                        "text/json": components["schemas"]["BooleanBaseResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/beneficiarymanagement/bank-name-enquiry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bank name enquiry */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["BankNameEnquiryQuery"];
                    "application/json": components["schemas"]["BankNameEnquiryQuery"];
                    "text/json": components["schemas"]["BankNameEnquiryQuery"];
                    "application/*+json": components["schemas"]["BankNameEnquiryQuery"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StringBaseResponse"];
                        "application/json": components["schemas"]["StringBaseResponse"];
                        "text/json": components["schemas"]["StringBaseResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/common/banks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all banks */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BankModelListBaseResponse"];
                        "application/json": components["schemas"]["BankModelListBaseResponse"];
                        "text/json": components["schemas"]["BankModelListBaseResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallets/{walletId}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get transactions for a wallet */
        get: {
            parameters: {
                query?: {
                    TransactionType?: components["schemas"]["TransactionTypeEnums"];
                    StartDate?: string;
                    EndDate?: string;
                    PageNumber?: number;
                    PageSize?: number;
                    SearchKey?: string;
                };
                header?: never;
                path: {
                    walletId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TransactionModelPagedListBaseResponse"];
                        "application/json": components["schemas"]["TransactionModelPagedListBaseResponse"];
                        "text/json": components["schemas"]["TransactionModelPagedListBaseResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallets/my-wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user's wallet */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WalletModelBaseResponse"];
                        "application/json": components["schemas"]["WalletModelBaseResponse"];
                        "text/json": components["schemas"]["WalletModelBaseResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallets/{walletId}/withdraw-fund": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Withdraw funds from the user's wallet */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    walletId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["WithdrawFundCommand"];
                    "application/json": components["schemas"]["WithdrawFundCommand"];
                    "text/json": components["schemas"]["WithdrawFundCommand"];
                    "application/*+json": components["schemas"]["WithdrawFundCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BooleanBaseResponse"];
                        "application/json": components["schemas"]["BooleanBaseResponse"];
                        "text/json": components["schemas"]["BooleanBaseResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountLookUpModel: {
            accountname?: string | null;
            status?: string | null;
            status_desc?: string | null;
        };
        AccountLookUpQuery: {
            accountNumber?: string | null;
        };
        BankModel: {
            name?: string | null;
            code?: string | null;
        };
        BankModelListBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["BankModel"][] | null;
            metaData?: unknown;
        };
        BankNameEnquiryQuery: {
            accountNumber: string | null;
            bankCode: string | null;
        };
        BeneficiaryModel: {
            name?: string | null;
            accountNumber?: string | null;
            bankName?: string | null;
            bankCode?: string | null;
        };
        BeneficiaryModelBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["BeneficiaryModel"];
            metaData?: unknown;
        };
        BeneficiaryModelPagedListBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["BeneficiaryModel"][] | null;
            metaData?: unknown;
        };
        BlockAccountCommand: {
            accountnumber?: string | null;
            blockreason?: string | null;
        };
        BlockAccountModel: {
            message?: string | null;
        };
        BooleanBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: boolean;
            metaData?: unknown;
        };
        CreateBeneficiaryCommand: {
            accountNumber: string | null;
            bankCode: string | null;
            name: string | null;
        };
        GetKYCDetailsQuery: {
            accountnumber?: string | null;
        };
        KYCDetailsModel: {
            accountname?: string | null;
            mobilenumber?: string | null;
            /** Format: double */
            walletbalance?: number;
            bvn?: string | null;
            nin?: string | null;
            status_desc?: string | null;
        };
        MiniStatementModel: {
            transactions?: components["schemas"]["MiniStatementTransactionModel"][] | null;
        };
        MiniStatementQuery: {
            accountnumber?: string | null;
        };
        MiniStatementTransactionModel: {
            recipientaccountNo?: string | null;
            bankName?: string | null;
            /** Format: double */
            amount?: number;
            /** Format: date-time */
            transactionDate?: string;
        };
        StringBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: string | null;
            metaData?: unknown;
        };
        TransactionModel: {
            transactionReference: string | null;
            narration?: string | null;
            transactionType?: components["schemas"]["TransactionTypeEnums"];
            /** Format: double */
            amount?: number;
            /** Format: date-time */
            transactionDate?: string;
            /** Format: date-span */
            transactionTime?: string;
            sourceBank?: string | null;
            sourceAccountName?: string | null;
            destinationBank?: string | null;
            destinationAccountName?: string | null;
        };
        TransactionModelPagedListBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["TransactionModel"][] | null;
            metaData?: unknown;
        };
        TransactionNotificationCommand: {
            originatoraccountnumber?: string | null;
            amount?: string | null;
            originatorname?: string | null;
            narration?: string | null;
            craccountname?: string | null;
            paymentreference?: string | null;
            bankname?: string | null;
            sessionid?: string | null;
            craccount?: string | null;
            bankcode?: string | null;
        };
        TransactionNotificationModel: {
            transactionReference?: string | null;
            status?: string | null;
            status_desc?: string | null;
        };
        /** @enum {string} */
        TransactionTypeEnums: "Credit" | "Debit";
        UnblockAccountCommand: {
            accountnumber?: string | null;
        };
        WalletModel: {
            accountNumber: string | null;
            /** Format: double */
            availableBalance?: number;
            bankName?: string | null;
            currency?: string | null;
            walletName?: string | null;
            isWalletPinSetup?: boolean;
        };
        WalletModelBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["WalletModel"];
            metaData?: unknown;
        };
        WithdrawFundCommand: {
            beneficiaryAccountNumber: string | null;
            /** Format: double */
            amount?: number;
            walletId?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
