/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new Treva account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["RegisterCommand"];
                    "application/json": components["schemas"]["RegisterCommand"];
                    "text/json": components["schemas"]["RegisterCommand"];
                    "application/*+json": components["schemas"]["RegisterCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StringBaseResponse"];
                        "application/json": components["schemas"]["StringBaseResponse"];
                        "text/json": components["schemas"]["StringBaseResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login to your account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["LoginCommand"];
                    "application/json": components["schemas"]["LoginCommand"];
                    "text/json": components["schemas"]["LoginCommand"];
                    "application/*+json": components["schemas"]["LoginCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LoginModelBaseResponse"];
                        "application/json": components["schemas"]["LoginModelBaseResponse"];
                        "text/json": components["schemas"]["LoginModelBaseResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Initiate forgot password procedure */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["ForgotPasswordCommand"];
                    "application/json": components["schemas"]["ForgotPasswordCommand"];
                    "text/json": components["schemas"]["ForgotPasswordCommand"];
                    "application/*+json": components["schemas"]["ForgotPasswordCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StringBaseResponse"];
                        "application/json": components["schemas"]["StringBaseResponse"];
                        "text/json": components["schemas"]["StringBaseResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset your account password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["ResetPasswordCommand"];
                    "application/json": components["schemas"]["ResetPasswordCommand"];
                    "text/json": components["schemas"]["ResetPasswordCommand"];
                    "application/*+json": components["schemas"]["ResetPasswordCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StringBaseResponse"];
                        "application/json": components["schemas"]["StringBaseResponse"];
                        "text/json": components["schemas"]["StringBaseResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh your access token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["RefreshTokenCommand"];
                    "application/json": components["schemas"]["RefreshTokenCommand"];
                    "text/json": components["schemas"]["RefreshTokenCommand"];
                    "application/*+json": components["schemas"]["RefreshTokenCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LoginModelBaseResponse"];
                        "application/json": components["schemas"]["LoginModelBaseResponse"];
                        "text/json": components["schemas"]["LoginModelBaseResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify user account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["VerifyAccountCommand"];
                    "application/json": components["schemas"]["VerifyAccountCommand"];
                    "text/json": components["schemas"]["VerifyAccountCommand"];
                    "application/*+json": components["schemas"]["VerifyAccountCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StringBaseResponse"];
                        "application/json": components["schemas"]["StringBaseResponse"];
                        "text/json": components["schemas"]["StringBaseResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change your account password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["ChangePasswordCommand"];
                    "application/json": components["schemas"]["ChangePasswordCommand"];
                    "text/json": components["schemas"]["ChangePasswordCommand"];
                    "application/*+json": components["schemas"]["ChangePasswordCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StringBaseResponse"];
                        "application/json": components["schemas"]["StringBaseResponse"];
                        "text/json": components["schemas"]["StringBaseResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get states */
        get: {
            parameters: {
                query?: {
                    Country?: string;
                    PageNumber?: number;
                    PageSize?: number;
                    SearchKey?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StateModelPagedListBaseResponse"];
                        "application/json": components["schemas"]["StateModelPagedListBaseResponse"];
                        "text/json": components["schemas"]["StateModelPagedListBaseResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get cities */
        get: {
            parameters: {
                query?: {
                    State?: string;
                    PageNumber?: number;
                    PageSize?: number;
                    SearchKey?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CityModelPagedListBaseResponse"];
                        "application/json": components["schemas"]["CityModelPagedListBaseResponse"];
                        "text/json": components["schemas"]["CityModelPagedListBaseResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/professions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all professions */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProfessionModelIEnumerableBaseResponse"];
                        "application/json": components["schemas"]["ProfessionModelIEnumerableBaseResponse"];
                        "text/json": components["schemas"]["ProfessionModelIEnumerableBaseResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/{subscriptionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Subscription by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    subscriptionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SubscriptionModelBaseResponse"];
                        "application/json": components["schemas"]["SubscriptionModelBaseResponse"];
                        "text/json": components["schemas"]["SubscriptionModelBaseResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Subscriptions */
        get: {
            parameters: {
                query?: {
                    Name?: string;
                    Amount?: number;
                    PageNumber?: number;
                    PageSize?: number;
                    SearchKey?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SubscriptionModelPagedListBaseResponse"];
                        "application/json": components["schemas"]["SubscriptionModelPagedListBaseResponse"];
                        "text/json": components["schemas"]["SubscriptionModelPagedListBaseResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/save-client-onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save client onboarding */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        Photo?: string;
                        /** Format: uuid */
                        StateId?: string;
                        /** Format: uuid */
                        CityId?: string;
                        Address?: string;
                        WebsiteUrl?: string;
                        LinkedIn?: string;
                        Instagram?: string;
                        Facebook?: string;
                        X?: string;
                        TikTok?: string;
                        Bio?: string;
                        /** Format: int32 */
                        CurrentStep?: number;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UnitBaseResponse"];
                        "application/json": components["schemas"]["UnitBaseResponse"];
                        "text/json": components["schemas"]["UnitBaseResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/client-onboarding-record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get client onboarding */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TempClientOnboardingModelBaseResponse"];
                        "application/json": components["schemas"]["TempClientOnboardingModelBaseResponse"];
                        "text/json": components["schemas"]["TempClientOnboardingModelBaseResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/save-creative-onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save creative onboarding */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        Cv?: string;
                        PortfolioLink?: string;
                        LinkedIn?: string;
                        Instagram?: string;
                        Facebook?: string;
                        X?: string;
                        TikTok?: string;
                        Bio?: string;
                        /** Format: uuid */
                        SubscriptionId?: string;
                        /** Format: int32 */
                        CurrentStep?: number;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UnitBaseResponse"];
                        "application/json": components["schemas"]["UnitBaseResponse"];
                        "text/json": components["schemas"]["UnitBaseResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/creative-onboarding-record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get creative onboarding */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TempCreativeOnboardingModelBaseResponse"];
                        "application/json": components["schemas"]["TempCreativeOnboardingModelBaseResponse"];
                        "text/json": components["schemas"]["TempCreativeOnboardingModelBaseResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/creatives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get creatives */
        get: {
            parameters: {
                query?: {
                    PageNumber?: number;
                    PageSize?: number;
                    SearchKey?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserCreativeModelPagedListBaseResponse"];
                        "application/json": components["schemas"]["UserCreativeModelPagedListBaseResponse"];
                        "text/json": components["schemas"]["UserCreativeModelPagedListBaseResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        AccountTypeEnums: "Company" | "Individual";
        /** @enum {string} */
        ActorTypeEnums: "Client" | "Creative";
        ChangePasswordCommand: {
            currentPassword: string | null;
            newPassword: string | null;
            confirmNewPassword: string | null;
        };
        CityModel: {
            /** Format: uuid */
            id?: string;
            name: string | null;
        };
        CityModelPagedListBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["CityModel"][] | null;
            metaData?: unknown;
        };
        /** @enum {string} */
        CompanySizeEnums: "ElevenToFifty" | "FiftyOneToTwoHundred" | "FiveHundredOneToThousand" | "NotSet" | "OneToTen" | "ThousandOneToTwoThousand" | "TwoHundredOneToFiveHundred" | "TwoThousandPlus";
        ForgotPasswordCommand: {
            email: string | null;
        };
        LoginCommand: {
            email: string | null;
            password: string | null;
        };
        LoginModel: {
            email: string | null;
            userId: string | null;
            accessToken: string | null;
            refreshToken: string | null;
            /** Format: date-time */
            expiry?: string;
            roles?: string[] | null;
        };
        LoginModelBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["LoginModel"];
            metaData?: unknown;
        };
        ProfessionModel: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
        };
        ProfessionModelIEnumerableBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["ProfessionModel"][] | null;
            metaData?: unknown;
        };
        RefreshTokenCommand: {
            expiredToken: string | null;
            refreshToken: string | null;
        };
        RegisterCommand: {
            actorType?: components["schemas"]["ActorTypeEnums"];
            accountType?: components["schemas"]["AccountTypeEnums"];
            companySize?: components["schemas"]["CompanySizeEnums"];
            companyName?: string | null;
            email: string | null;
            firstName: string | null;
            lastName: string | null;
            middleName?: string | null;
            countryCode?: string | null;
            phoneNumber?: string | null;
            agreedToTerms?: boolean;
            password: string | null;
            /** Format: uuid */
            professionId?: string | null;
        };
        ResetPasswordCommand: {
            email: string | null;
            newPassword: string | null;
            token: string | null;
        };
        StateModel: {
            /** Format: uuid */
            id?: string;
            name: string | null;
        };
        StateModelPagedListBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["StateModel"][] | null;
            metaData?: unknown;
        };
        StringBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: string | null;
            metaData?: unknown;
        };
        SubscriptionFeatureModel: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            description?: string | null;
        };
        SubscriptionModel: {
            /** Format: uuid */
            id?: string;
            title?: string | null;
            subTitle?: string | null;
            /** Format: double */
            amount?: number;
            /** Format: int32 */
            durationInDays?: number;
            currency?: string | null;
            period?: string | null;
            description?: string | null;
            color?: string | null;
            features?: components["schemas"]["SubscriptionFeatureModel"][] | null;
        };
        SubscriptionModelBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["SubscriptionModel"];
            metaData?: unknown;
        };
        SubscriptionModelPagedListBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["SubscriptionModel"][] | null;
            metaData?: unknown;
        };
        TempClientOnboardingModel: {
            photoUrl?: string | null;
            /** Format: uuid */
            stateId?: string | null;
            /** Format: uuid */
            cityId?: string | null;
            address?: string | null;
            websiteUrl?: string | null;
            linkedIn?: string | null;
            instagram?: string | null;
            facebook?: string | null;
            x?: string | null;
            tikTok?: string | null;
            bio?: string | null;
            /** Format: int32 */
            currentStep?: number;
            /** Format: int32 */
            totalSteps?: number;
            isCompleted?: boolean;
        };
        TempClientOnboardingModelBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["TempClientOnboardingModel"];
            metaData?: unknown;
        };
        TempCreativeOnboardingModel: {
            cvUrl?: string | null;
            portfolioLink?: string | null;
            linkedIn?: string | null;
            instagram?: string | null;
            facebook?: string | null;
            x?: string | null;
            tikTok?: string | null;
            bio?: string | null;
            /** Format: uuid */
            subscriptionPlan?: string | null;
            /** Format: int32 */
            currentStep?: number;
            /** Format: int32 */
            totalSteps?: number;
            isCompleted?: boolean;
        };
        TempCreativeOnboardingModelBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["TempCreativeOnboardingModel"];
            metaData?: unknown;
        };
        Unit: Record<string, never>;
        UnitBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["Unit"];
            metaData?: unknown;
        };
        UserCreativeModel: {
            id?: string | null;
            name?: string | null;
            profession?: string | null;
            profilePicture?: string | null;
            /** Format: double */
            averageRating?: number;
            /** Format: int32 */
            totalRatings?: number;
        };
        UserCreativeModelPagedListBaseResponse: {
            isSuccess?: boolean;
            statusCode?: string | null;
            message?: string | null;
            data?: components["schemas"]["UserCreativeModel"][] | null;
            metaData?: unknown;
        };
        VerifyAccountCommand: {
            email: string | null;
            token: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
